export type JobStatus = "open" | "closed";
export type ApplicantStatus = "new" | "reviewed" | "shortlisted" | "rejected";

export type Job = {
  id: string;
  title: string;
  department: string;
  description: string;
  requirements: string;
  employment_type?: string | null;
  location?: string | null;
  remote_type?: string | null;
  skills_required: string[];
  preferred_skills?: string[] | null;
  must_have_skills?: string[] | null;
  tools_technologies?: string[] | null;
  certifications?: string[] | null;
  required_experience_years?: number | null;
  experience_required: string;
  education_level?: string | null;
  seniority_level?: string | null;
  skills_weight?: number | null;
  experience_weight?: number | null;
  education_weight?: number | null;
  projects_weight?: number | null;
  communication_weight?: number | null;
  minimum_score_threshold?: number | null;
  auto_shortlist?: boolean | null;
  auto_reject?: boolean | null;
  disqualifying_keywords?: string[] | null;
  screening_questions?: string[] | null;
  salary_min?: number | null;
  salary_max?: number | null;
  currency?: string | null;
  deadline: string | null;
  start_date?: string | null;
  questions: string[];
  status: JobStatus;
  created_at: string;
};

export type Applicant = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  job_id: string;
  cv_url: string;
  photo_url: string | null;
  answers: Record<string, string> | null;
  ai_score: number | null;
  ai_summary: string | null;
  ai_strengths: string[] | null;
  ai_weaknesses: string[] | null;
  ai_decision: string | null;
  ai_missing_requirements: string[] | null;
  ai_questions: string[] | null;
  ai_improvements: string[] | null;
  salary_expectation?: number | null;
  salary_currency?: string | null;
  status: ApplicantStatus;
  created_at: string;
};

export type ApplicationStatus = "submitted" | "reviewed" | "shortlisted" | "rejected";

export type Application = {
  id: string;
  job_id: string;
  full_name: string;
  email: string;
  phone: string | null;
  location: string | null;
  cv_url: string;
  cv_text: string | null;
  answers: Record<string, string> | null;
  salary_expectation: number | null;
  salary_currency: string | null;
  ai_score: number | null;
  ai_decision: string | null;
  ai_summary: string | null;
  ai_strengths: string[] | null;
  ai_weaknesses: string[] | null;
  ai_missing: string[] | null;
  ai_questions: string[] | null;
  ai_improvements: string[] | null;
  status: ApplicationStatus;
  created_at: string;
};
